# main.py — Generated by VIA for: Create a full-stack expense tracker where I can add, view, and delete my daily expenses. Use React for the frontend and Python FastAPI with a database for the backend. Keep the UI clean and modern with an analytics dashboard.
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from database import engine, get_db
from models import Base, Item
from sqlalchemy.orm import Session
import os

app = FastAPI(
    title="Create A Full Stack Expense Tracker",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def on_startup():
    try:
        Base.metadata.create_all(bind=engine)
    except Exception as e:
        import logging as _log
        _log.getLogger("via").warning(f"DB init warning: {e}")



@app.get("/")
def root():
    return {"app": "Create A Full Stack Expense Tracker", "status": "running", "docs": "/docs", "api": "/api/v1/items"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/items")
def get_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Item).offset(skip).limit(limit).all()
    return {"items": [{"id": i.id, "title": i.title, "description": i.description,
                       "status": i.status, "amount": i.amount, "category": i.category,
                       "created_at": str(i.created_at)} for i in items],
            "total": db.query(Item).count()}

@app.get("/api/v1/items/{item_id}")
def get_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"id": item.id, "title": item.title, "description": item.description,
            "status": item.status, "amount": item.amount, "category": item.category,
            "created_at": str(item.created_at)}

@app.post("/api/v1/items")
def create_item(payload: dict, db: Session = Depends(get_db)):
    item = Item(
        title=payload.get("title", "Untitled"),
        description=payload.get("description", ""),
        status=payload.get("status", "active"),
        amount=float(payload.get("amount", 0.0)),
        category=payload.get("category", "General"),
    )
    db.add(item); db.commit(); db.refresh(item)
    return {"id": item.id, "title": item.title, "description": item.description,
            "status": item.status, "amount": item.amount, "category": item.category,
            "created_at": str(item.created_at)}

@app.put("/api/v1/items/{item_id}")
def update_item(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"id": item.id, "title": item.title, "amount": item.amount, "category": item.category}

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

@app.get("/api/v1/stats")
def get_stats(db: Session = Depends(get_db)):
    from sqlalchemy import func as sqlfunc
    total  = db.query(Item).count()
    active = db.query(Item).filter(Item.status == "active").count()
    total_amount = db.query(sqlfunc.sum(Item.amount)).scalar() or 0.0
    by_category  = db.query(Item.category, sqlfunc.sum(Item.amount)).group_by(Item.category).all()
    return {"total": total, "active": active, "total_amount": total_amount,
            "by_category": {cat: float(amt) for cat, amt in by_category}}

# ── Route aliases: /api/v1/expenses and /expenses mirror /api/v1/items ────
@app.get("/api/v1/expenses")
def alias_get_expenses(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_items(skip=skip, limit=limit, db=db)

@app.post("/api/v1/expenses")
def alias_create_expenses(payload: dict, db: Session = Depends(get_db)):
    return create_item(payload=payload, db=db)

@app.get("/api/v1/expenses/{item_id}")
def alias_get_expenses_one(item_id: int, db: Session = Depends(get_db)):
    return get_item(item_id=item_id, db=db)

@app.put("/api/v1/expenses/{item_id}")
def alias_update_expenses(item_id: int, payload: dict, db: Session = Depends(get_db)):
    return update_item(item_id=item_id, payload=payload, db=db)

@app.delete("/api/v1/expenses/{item_id}")
def alias_delete_expenses(item_id: int, db: Session = Depends(get_db)):
    return delete_item(item_id=item_id, db=db)

@app.get("/expenses")
def alias_get_expenses_short(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_items(skip=skip, limit=limit, db=db)

@app.post("/expenses")
def alias_create_expenses_short(payload: dict, db: Session = Depends(get_db)):
    return create_item(payload=payload, db=db)

@app.get("/expenses/{item_id}")
def alias_get_expenses_short_one(item_id: int, db: Session = Depends(get_db)):
    return get_item(item_id=item_id, db=db)

@app.put("/expenses/{item_id}")
def alias_update_expenses_short(item_id: int, payload: dict, db: Session = Depends(get_db)):
    return update_item(item_id=item_id, payload=payload, db=db)

@app.delete("/expenses/{item_id}")
def alias_delete_expenses_short(item_id: int, db: Session = Depends(get_db)):
    return delete_item(item_id=item_id, db=db)


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
